### ISSUE TITLE
Archive Posts

### ISSUE THREAD

**Issue by tautropfli** [timetabio/code#26]
Quoting from https://elementary.io/docs/human-interface-guidelines#always-provide-an-undo

> Deleting an item. Instead of asking the user if they are sure, make the item "disappear" from the app, but provide an easy and intuitive way to undo the delete.

Items are moved to a "deleted" state and deleted after 30 days.
This idea also seems worth mentioning/documenting in the Documentation

- Provide undo button when deleting a post like with a nifty crumbs bar at the bottom of the screen

**TODO**:
- [x] Add `archived` field to `posts`
- [x] Implement archive / unarchive endpoints
- [x] Implement cleanup cron
- [x] Show archived banner on post detail page
- [x] Show undo toast on feed page when deleting update `<ajax-form>`  to accept json in form of 
```json
{
    "toast": {
        "message": "The post has been archived, it will be deleted after 30 days",
        "action": {
            "icon": "action-undo",
            "label": "Undo",
            "post": "/action/unarchive?post_id=foobar"
        }
    }
}
```
- [x] Update `Timetabio\Frontend\Handlers\Post\DeletePost\CommandHandler`: reload instead of redirect
- [x] Update `\Timetabio\Frontend\Models\Action\DeletePostModel`: Remove `feedId`
- [x] Update `\Timetabio\Frontend\Renderers\Snippet\PostSnippet`: Remove `feed_id` from `$deleteButtonData`
